version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: maven_central_credentials

jobs:
  build:

    working_directory: ~/span

    docker:
      - image: cimg/openjdk:8.0.322

    steps:
      - checkout

      - restore_cache:
          key: circleci-java-span-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache: # saves the project dependencies
          paths:
            - ~/.m2
          key: circleci-java-span-{{ checksum "pom.xml" }}

      - run: mvn install

      - run: mvn --settings ".circleci/settings.xml" deploy -e -X
